repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^src/
        args: [--ignore-missing-imports, --no-error-summary, --disable-error-code=no-untyped-def, --disable-error-code=var-annotated, --disable-error-code=assignment, --disable-error-code=attr-defined, --disable-error-code=union-attr, --disable-error-code=operator, --disable-error-code=misc, --disable-error-code=arg-type, --disable-error-code=no-any-return, --disable-error-code=import-untyped, --disable-error-code=name-defined, --disable-error-code=unreachable]
        additional_dependencies: [types-requests, types-PyYAML, types-python-dateutil]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [manual]
