"""Tool Usage Service for Sandroid.

This service tracks which analysis tools were used during a session
and what files they generated, for exit summary and reporting.

Extracted from Toolbox class to follow Single Responsibility Principle.

Usage:
    from sandroid.services import get_tool_usage_service
    from sandroid.services.tool_usage_service import ToolUsageService

    # Get service
    usage = get_tool_usage_service()

    # Mark tool as used with files
    usage.mark_used("screenshots", files=["/path/to/screenshot.png"])

    # Get usage summary
    summary = usage.get_summary_dict()
"""

import logging
import os
import threading
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from sandroid.services.protocols import EventBusProtocol

logger = logging.getLogger(__name__)


@dataclass
class ToolUsage:
    """Represents usage information for a single tool.

    Attributes:
        name: Tool identifier (e.g., "screenshots", "network_capture")
        display_name: Human-readable name for display
        used: Whether the tool was used
        files: List of files generated by this tool
        first_used: When the tool was first used
        use_count: How many times the tool was used
    """

    name: str
    display_name: str = ""
    used: bool = True
    files: list[str] = field(default_factory=list)
    first_used: datetime = field(default_factory=datetime.now)
    use_count: int = 1

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "name": self.name,
            "display_name": self.display_name or self.name,
            "used": self.used,
            "files": self.files,
            "first_used": self.first_used.isoformat(),
            "use_count": self.use_count,
        }


class ToolUsageService:
    """Service for tracking tool usage during analysis sessions.

    This service tracks:
    - Which tools were used during the session
    - What files each tool generated
    - Usage counts and timing

    Thread Safety:
        This service is thread-safe. All operations are protected by locks.

    Example:
        # Basic usage
        service = ToolUsageService()

        # Mark tool as used
        service.mark_used("fritap", files=["/results/fritap.pcap"])

        # Check if tool was used
        if service.is_used("fritap"):
            print("FriTap was used")

        # Get summary for exit display
        for tool, info in service.get_usage().items():
            print(f"{tool}: {len(info['files'])} files")
    """

    def __init__(self, event_bus: EventBusProtocol | None = None):
        """Initialize ToolUsageService.

        Args:
            event_bus: Optional event bus for state change notifications.
        """
        self._event_bus = event_bus
        self._logger = logger
        self._lock = threading.Lock()
        self._tools: dict[str, ToolUsage] = {}

    def mark_used(
        self,
        tool_name: str,
        files: list[str] | None = None,
        display_name: str | None = None,
    ) -> None:
        """Mark a tool as used and optionally track its output files.

        Args:
            tool_name: Internal tool identifier.
            files: Optional list of file paths generated by this tool.
            display_name: Optional human-readable name for display.
        """
        with self._lock:
            if tool_name not in self._tools:
                self._tools[tool_name] = ToolUsage(
                    name=tool_name,
                    display_name=display_name or tool_name,
                )
            else:
                self._tools[tool_name].use_count += 1

            if files:
                self._tools[tool_name].files.extend(files)

        self._logger.debug(f"Tool used: {tool_name}, files: {files}")

    def is_used(self, tool_name: str) -> bool:
        """Check if a tool was used during the session.

        Args:
            tool_name: Tool identifier to check.

        Returns:
            True if the tool was used.
        """
        with self._lock:
            return tool_name in self._tools

    def get_usage(self) -> dict[str, dict[str, Any]]:
        """Get dictionary of all tools used during this session.

        Returns:
            Dictionary mapping tool names to their usage info.
            Format: {"tool_name": {"used": True, "files": [...]}}
        """
        with self._lock:
            # Return in legacy format for backwards compatibility
            return {
                name: {"used": tool.used, "files": tool.files.copy()}
                for name, tool in self._tools.items()
            }

    def get_tool_info(self, tool_name: str) -> ToolUsage | None:
        """Get detailed usage info for a specific tool.

        Args:
            tool_name: Tool identifier.

        Returns:
            ToolUsage instance or None if not used.
        """
        with self._lock:
            return self._tools.get(tool_name)

    def get_files(self, tool_name: str) -> list[str]:
        """Get list of files generated by a specific tool.

        Args:
            tool_name: Tool identifier.

        Returns:
            List of file paths (empty if tool not used).
        """
        with self._lock:
            tool = self._tools.get(tool_name)
            return tool.files.copy() if tool else []

    def get_all_files(self) -> list[str]:
        """Get list of all files generated by all tools.

        Returns:
            Flat list of all file paths.
        """
        with self._lock:
            files = []
            for tool in self._tools.values():
                files.extend(tool.files)
            return files

    def get_tool_names(self) -> list[str]:
        """Get list of all tools that were used.

        Returns:
            List of tool identifiers.
        """
        with self._lock:
            return list(self._tools.keys())

    def get_summary_string(self, results_path: str | None = None) -> str:
        """Generate a summary string for exit display.

        Args:
            results_path: Base path for calculating relative paths.
                         Defaults to RESULTS_PATH environment variable.

        Returns:
            Formatted summary string.
        """
        if results_path is None:
            results_path = os.getenv("RESULTS_PATH", "results/")

        with self._lock:
            if not self._tools:
                return ""

            lines = ["Generated files by tool:"]
            for tool_name, tool in self._tools.items():
                if tool.files:
                    display = tool.display_name or tool_name
                    lines.append(f"  {display}:")
                    for file_path in tool.files:
                        if file_path and os.path.exists(file_path):
                            try:
                                rel_path = os.path.relpath(file_path, results_path)
                                lines.append(f"    - {rel_path}")
                            except ValueError:
                                # Can happen on Windows with different drives
                                lines.append(f"    - {file_path}")
                        elif file_path:
                            lines.append(f"    - {file_path} (not found)")

            return "\n".join(lines)

    def count(self) -> int:
        """Get the number of unique tools used.

        Returns:
            Number of tools.
        """
        with self._lock:
            return len(self._tools)

    def total_files(self) -> int:
        """Get total count of files generated by all tools.

        Returns:
            Total file count.
        """
        with self._lock:
            return sum(len(tool.files) for tool in self._tools.values())

    def get_state_dict(self) -> dict[str, Any]:
        """Get service state as a dictionary.

        Useful for API responses and debugging.

        Returns:
            Dictionary with service state.
        """
        with self._lock:
            return {
                "tool_count": len(self._tools),
                "total_files": sum(len(t.files) for t in self._tools.values()),
                "tools": {name: tool.to_dict() for name, tool in self._tools.items()},
            }

    def reset(self) -> None:
        """Reset service state.

        Clears all tool usage data. Useful for testing.
        """
        with self._lock:
            self._tools.clear()

    def clear(self) -> None:
        """Alias for reset() to match other services."""
        self.reset()


__all__ = ["ToolUsage", "ToolUsageService"]
